### ISSUE TITLE
Pipeline crashes at `Extract1dStep`

### ISSUE THREAD

**Issue by lheinke** [radicamc/supreme-spoon#21]
I have been running the pipeline using the installation procedure described in issue #20 and the `run_DMS.yaml` setup. It crashes at the `Extract1dStep`:

```
2023-08-24 07:43:43,878 - stpipe.Extract1dStep - INFO - Extract1dStep instance created.
Traceback (most recent call last):
  File "/home/lheinke/Data/JWST/run_DMS.py", line 98, in <module>
    stage2_results = run_stage2(stage1_results,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lheinke/.local/miniconda3/envs/supreme_spoon/lib/python3.11/site-packages/supreme_spoon-1.1.1-py3.11.egg/supreme_spoon/stage2.py", line 1526, in run_stage2
  File "/home/lheinke/.local/miniconda3/envs/supreme_spoon/lib/python3.11/site-packages/supreme_spoon-1.1.1-py3.11.egg/supreme_spoon/stage2.py", line 336, in run
  File "/home/lheinke/.local/miniconda3/envs/supreme_spoon/lib/python3.11/site-packages/supreme_spoon-1.1.1-py3.11.egg/supreme_spoon/stage2.py", line 850, in tracingstep
  File "/home/lheinke/.local/miniconda3/envs/supreme_spoon/lib/python3.11/site-packages/supreme_spoon-1.1.1-py3.11.egg/supreme_spoon/utils.py", line 476, in get_trace_centroids
  File "/home/lheinke/.local/miniconda3/envs/supreme_spoon/lib/python3.11/site-packages/applesoss-2.0.0-py3.11.egg/applesoss/edgetrigger_centroids.py", line 1071, in get_soss_centroids
  File "/home/lheinke/.local/miniconda3/envs/supreme_spoon/lib/python3.11/site-packages/applesoss-2.0.0-py3.11.egg/applesoss/edgetrigger_centroids.py", line 295, in get_centroids_edgetrigger
  File "/home/lheinke/.local/miniconda3/envs/supreme_spoon/lib/python3.11/site-packages/applesoss-2.0.0-py3.11.egg/applesoss/edgetrigger_utils.py", line 146, in get_image_dim
  File "/home/lheinke/.local/miniconda3/envs/supreme_spoon/lib/python3.11/site-packages/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```

I checked the APPLESOSS repository and found issue https://github.com/radicamc/applesoss/issues/7 which seems to be exactly the problem I encountered. Looking at the day of the fix April 3 it becomes clear that it is not part of the most recent 2.0.0 release from March 13 that also gets installed via `pip` when installing supreme-SPOON.

Manually installing the package `applesoss` from GitHub fixes the issue as expected.

**Comment by lheinke** [comment]
The installation finishes without problems when just using `pip install supreme_spoon` within an identical `conda` environment.

**Comment by radicamc** [comment]
Proper applesoss version (v2.0.2) has been pushed to PyPI
